name: CI to Docker Hub
on:
  push:
    branches:
    - master
  schedule:
    - cron: 0 0 * * 1

jobs:
  build:
    name: PHP-${{ matrix.php_version }}
    strategy:
      matrix:
        php_version:
        - '7.3'
        - '7.4'
        - '8.0'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login to Docker Hub
        run: docker login --username $DOCKER_USER --password $DOCKER_PASS
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

      - name: Build
        run: docker build --build-arg VERSION=${{ matrix.php_version }} -t rust17/php-docker-action:${{ matrix.php_version }} .

      - name: Push
        run: docker push rust17/php-docker-action:${{ matrix.php_version }}